export interface ParsedMediaMessage {
  isMedia: boolean;
  mediaType?: 'image' | 'audio' | 'document' | 'video';
  mediaUrl?: string;
  filename?: string;
  caption: string;
  footer?: string;
  buttons?: string[];
  localPath?: string;
  quotedMessage?: string;
}

/**
 * Parses message text to detect prefix-based media markers and templates elements.
 * Format examples:
 * - [media:image:https://example.com/img.jpg]Optional Caption\n[footer:ScaleCraft AI]\n[button:Know About ScalCraft Agent]
 * - [media:audio:https://example.com/audio.ogg]
 * - [media:document:https://example.com/doc.pdf|Invoice.pdf]Please review
 */
export function parseMessageContent(text: string): ParsedMediaMessage {
  if (!text) {
    return { isMedia: false, caption: '' };
  }

  let workingText = text;

  // 1. Extract and strip footer tag
  let footer: string | undefined;
  const footerRegex = /\[footer:([^\]]+)\]/g;
  const footerMatch = footerRegex.exec(workingText);
  if (footerMatch) {
    footer = footerMatch[1];
    workingText = workingText.replace(footerRegex, '');
  }

  // 2. Extract and strip button tags
  const buttons: string[] = [];
  const buttonRegex = /\[button:([^\]]+)\]/g;
  let buttonMatch;
  while ((buttonMatch = buttonRegex.exec(workingText)) !== null) {
    buttons.push(buttonMatch[1]);
  }
  if (buttons.length > 0) {
    workingText = workingText.replace(buttonRegex, '');
  }

  // Clean up any remaining trailing/leading whitespace or newlines from stripping tags
  workingText = workingText.trim();

  // 2.5 Extract Quoted Message block (e.g. [Replying to your previous message: "..."])
  let quotedMessage: string | undefined;
  const quoteRegex = /\[Replying to (?:your )?previous message: "([\s\S]*?)"\]\s*/i;
  const quoteMatch = quoteRegex.exec(workingText);
  if (quoteMatch) {
    quotedMessage = quoteMatch[1];
    workingText = workingText.replace(quoteRegex, '').trim();
  }

  // Parse incoming media placeholders generated by Hermes
  // Format 1: [The user sent a video attachment: '1234.mp4'. It is saved at: /home/ubuntu/...]
  const hermesMediaRegex1 = /\[The user sent an? (video|image|audio|voice message|document) attachment: '([^']+)'. It is saved at: (.*?)\. Its content is not inlined here/i;
  // Format 2: [Image attached at: /home/ubuntu/...]
  const hermesMediaRegex2 = /\[(Image|Video|Audio|Voice|Document) attached at:\s*([^\]]+)\]/i;

  let parsedMediaType: 'image' | 'audio' | 'document' | 'video' | null = null;
  let filename = '';
  let localPath = '';
  let captionText = '';

  const hermesMatch1 = workingText.match(hermesMediaRegex1);
  const hermesMatch2 = workingText.match(hermesMediaRegex2);

  if (hermesMatch1) {
    const typeStr = hermesMatch1[1].toLowerCase();
    if (typeStr === 'image') parsedMediaType = 'image';
    else if (typeStr === 'video') parsedMediaType = 'video';
    else if (typeStr === 'audio' || typeStr === 'voice message') parsedMediaType = 'audio';
    else parsedMediaType = 'document';
    
    filename = hermesMatch1[2];
    localPath = hermesMatch1[3];
  } else if (hermesMatch2) {
    const typeStr = hermesMatch2[1].toLowerCase();
    if (typeStr === 'image') parsedMediaType = 'image';
    else if (typeStr === 'video') parsedMediaType = 'video';
    else if (typeStr === 'audio' || typeStr === 'voice') parsedMediaType = 'audio';
    else parsedMediaType = 'document';
    
    localPath = hermesMatch2[2].trim();
    filename = localPath.split('/').pop() || 'media';
    
    // Extract any caption before the attachment block
    captionText = workingText.substring(0, hermesMatch2.index).trim();
  }

  if (parsedMediaType && localPath) {
    const proxyUrl = `/api/dashboard/proxy-media?path=${encodeURIComponent(localPath)}`;
    return {
      isMedia: true,
      mediaType: parsedMediaType,
      mediaUrl: proxyUrl,
      filename,
      caption: captionText,
      localPath,
      footer,
      buttons,
      quotedMessage
    };
  }

  // Format 3: 🔊 Audio: /home/ubuntu/.hermes/cache/audio/audio_xxx.ogg
  const emojiAudioRegex = /🔊\s*Audio:\s*(\/home\/ubuntu\/[^\s]+)/i;
  const emojiAudioMatch = workingText.match(emojiAudioRegex);
  if (emojiAudioMatch) {
    const path = emojiAudioMatch[1].trim();
    const proxyUrl = `/api/dashboard/proxy-media?path=${encodeURIComponent(path)}`;
    const captionBefore = workingText.substring(0, emojiAudioMatch.index).trim();
    return {
      isMedia: true,
      mediaType: 'audio',
      mediaUrl: proxyUrl,
      filename: path.split('/').pop() || 'voice.ogg',
      caption: captionBefore,
      localPath: path,
      footer,
      buttons,
      quotedMessage
    };
  }

  // 3. Process the remaining text with the original media parser logic
  if (workingText.startsWith('[media:')) {
    const closeIndex = workingText.indexOf(']');
    if (closeIndex !== -1) {
      const mediaPart = workingText.slice(7, closeIndex);
      const caption = workingText.slice(closeIndex + 1).trim();

      const firstColon = mediaPart.indexOf(':');
      if (firstColon !== -1) {
        const type = mediaPart.slice(0, firstColon) as 'image' | 'audio' | 'document' | 'video';
        const payload = mediaPart.slice(firstColon + 1);

        if (type === 'image' || type === 'audio' || type === 'document' || type === 'video') {
          if (type === 'document' || type === 'video') {
            const pipeIndex = payload.indexOf('|');
            if (pipeIndex !== -1) {
              const url = payload.slice(0, pipeIndex);
              const filename = payload.slice(pipeIndex + 1);
              return {
                isMedia: true,
                mediaType: type,
                mediaUrl: url,
                filename: filename || 'Document',
                caption,
                footer,
                buttons,
                quotedMessage
              };
            }
            return {
              isMedia: true,
              mediaType: type,
              mediaUrl: payload,
              filename: 'Document',
              caption,
              footer,
              buttons,
              quotedMessage
            };
          }

          return {
            isMedia: true,
            mediaType: type,
            mediaUrl: payload,
            caption,
            footer,
            buttons,
            quotedMessage
          };
        }
      }
    }
  }

  return { isMedia: false, caption: workingText, footer, buttons, quotedMessage };
}

/**
 * Formats media properties into the standardized prefix-based message string.
 */
export function formatMediaMessage(
  type: 'image' | 'audio' | 'document' | 'video',
  url: string,
  filename?: string,
  caption?: string
): string {
  const cleanCaption = caption || '';
  if (type === 'document') {
    const cleanFilename = filename || 'Document';
    return `[media:document:${url}|${cleanFilename}]${cleanCaption}`;
  }
  if (type === 'video') {
    const cleanFilename = filename || 'Video';
    return `[media:video:${url}|${cleanFilename}]${cleanCaption}`;
  }
  return `[media:${type}:${url}]${cleanCaption}`;
}
