import React from 'react';
import Link from 'next/link';

export const metadata = {
  title: 'Terms of Service - ScaleCraft',
  description: 'Terms of Service for ScaleCraft WhatsApp AI Agent SaaS clients.',
};

export default function TermsOfServicePage() {
  return (
    <main className="min-h-screen bg-[#F7F7F5] text-[#111110] font-body py-16 px-6 sm:px-10">
      <div className="max-w-3xl mx-auto space-y-12">
        {/* Brand Header */}
        <div className="border-b border-[#EBEBEB] pb-8 space-y-4">
          <Link href="/" className="inline-block text-xl font-extrabold tracking-tight uppercase font-heading">
            ScaleCraft<span className="text-[#1B5E20]">.</span>
          </Link>
          <div className="space-y-1">
            <h1 className="text-3xl sm:text-4xl font-black font-heading tracking-tight">Terms of Service</h1>
            <p className="text-xs text-[#6F6E69] uppercase tracking-widest font-semibold">
              Effective Date: June 2026
            </p>
          </div>
        </div>

        {/* Content sections */}
        <div className="space-y-8 text-sm leading-relaxed text-[#3c3c3b]">
          
          <section className="space-y-3">
            <h2 className="text-lg font-bold text-[#111110] font-heading">1. Acceptance of Terms</h2>
            <p>
              By purchasing, deploying, or subscribing to our Managed WhatsApp AI Agent SaaS ("ScaleCraft Agent"), you agree to be bound by these Terms of Service. If you do not agree, you must not proceed with the subscription or use our services.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-[#111110] font-heading">2. Fees & Subscriptions</h2>
            <p>
              Our pricing model consists of a setup phase followed by a recurring monthly subscription:
            </p>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>Setup & Activation Fee:</strong> A one-time charge of <strong>₹6,999</strong>. This fee covers dedicated VPS provisioning, setup scripts configuration, and onboarding assistance. <strong>This fee is strictly non-refundable</strong> once server creation or script installation has started.</li>
              <li><strong>Monthly Subscription:</strong> A recurring charge of <strong>₹1,200/month</strong> for VPS hosting, maintenance, and dashboard software licenses. You can cancel your subscription at any time by providing a <strong>30-day notice</strong>.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-[#111110] font-heading">3. API Credentials & Key Requirements</h2>
            <p>
              To power the conversation reasoning of your AI Agent, you are required to provide your own <strong>Google Gemini API key</strong>. You are solely responsible for all usage charges and quotas associated with your Gemini API key. ScaleCraft is not responsible for any model downtime, quota limits, or bills generated by Google AI Studio.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-[#111110] font-heading">4. WhatsApp Policy & Compliance</h2>
            <p>
              You must comply with Meta's WhatsApp Terms of Service and Business Policy at all times:
            </p>
            <ul className="list-disc pl-5 space-y-2">
              <li>You must only link numbers you are authorized to use.</li>
              <li>You strictly agree not to use the agent for spamming, sending unsolicited mass marketing campaigns, or broadcasting illegal materials.</li>
              <li>You must respect opt-out requests from recipients immediately.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-[#111110] font-heading">5. Exclusion of Liability & Account Suspension</h2>
            <p>
              Connecting an automated bot to a personal or business WhatsApp number carries risks of account blocking by Meta. <strong>ScaleCraft is not liable or responsible in any way for any blocks, suspensions, or bans imposed on your WhatsApp number or Meta accounts.</strong> You choose to deploy and link the agent at your own business discretion.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-[#111110] font-heading">6. Governing Law</h2>
            <p>
              These Terms of Service are governed by and construed in accordance with the laws of <strong>Kerala, India</strong>, without regard to conflict of law principles. Any legal actions or proceedings arising from these terms shall be subject to the exclusive jurisdiction of courts located in Kerala.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-[#111110] font-heading">7. Contact Information</h2>
            <p>
              For legal inquiries, terms compliance, or billing cancellations, contact us:
            </p>
            <div className="bg-white border border-[#EBEBEB] rounded-2xl p-5 mt-2 space-y-1">
              <p className="font-bold text-[#111110]">ScaleCraft Legal & Compliance</p>
              <p>Email: <a href="mailto:support@thescalecraft.in" className="text-[#0055ff] hover:underline">support@thescalecraft.in</a></p>
              <p>WhatsApp Support: <a href="https://wa.me/918078004732" target="_blank" rel="noopener noreferrer" className="text-[#0055ff] hover:underline">+91 80780 04732</a></p>
            </div>
          </section>

        </div>

        {/* Footer Link */}
        <div className="border-t border-[#EBEBEB] pt-8 flex justify-between items-center text-xs text-[#AEACA5]">
          <span>© 2026 ScaleCraft. All rights reserved.</span>
          <Link href="/" className="text-[#0055ff] hover:underline font-bold">
            Back to Home
          </Link>
        </div>
      </div>
    </main>
  );
}
